WorkEffect.Website/Controllers/LayoutsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkEffect.Website.Data;
using WorkEffect.Website.Models;

namespace WorkEffect.Website.Controllers
{
    public class LayoutsController : BaseCmsEntityControllerAsync<ContentLayout>
    {
    }
}

WorkEffect.Website/Controllers/WorkEffectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkEffect.Website.Controllers
{
    public class WorkEffectController : Controller
    {
        // GET: WorkEffect
        public ActionResult Index()
        {
            return View();
        }
    }
}

WorkEffect.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:400,900,500,700' rel='stylesheet' type='text/css'>

    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/parallax")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body id="page-top">
    <header class="intro container-fluid" data-parallax="scroll" data-image-src="/Content/Images/bg_cut.png">
        <div class="intro-content-position">
            <div class="intro-heading-text" data-toggle="collapse" data-target="collapse">
                <div class="brand-heading">WorkEffect</div>
                <div>some fancy slogan?</div>
            </div>
            <div class="intro-logo">
            </div>
        </div>
    </header>

    <div class="nav-wrapper">
        <nav class="navbar navbar-inverse" data-spy="affix">
            <!-- data-offset-top="400"> -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle text-white" data-toggle="collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="collapse navbar-collapse navbar-center navbar-main-collapse">
                <ul class="nav navbar-nav text-white navbar-brand">
                    <li><a class="nav-active" href="@Url.Action("Index", "WorkEffect")">Work Effect</a></li>
                    <li><a href="#WorkEffect2">Welding</a></li>
                    <li><a href="#WorkEffect3">Fiber</a></li>
                    <li><a href="#WorkEffect4">Motorcycles</a></li>
                    <li><a href="#WorkEffect5">Racing</a></li>
                    <li> | admin:  </li>
                    <li><a href="@Url.Action("Index", "Layouts")">Layouts</a></li>
                </ul>
            </div>
        </nav>
    </div>

    @RenderBody()

    <footer class="footer text-white">
        <div class="row">
            <div class="col-md-6 footer-left">
                Work Effect GmbH |
                Uetendorf |
                Glütschbachstrasse 22b |
                3661 Uetendorf
            </div>
            <div class="col-md-6 footer-right">
                Benjamin Emmenegger |
                B.Emmenegger@WorkEffect.ch |
                +41 79 353 36 60
            </div>
        </div>
    </footer>

    <script type="text/javascript">
        $(document).ready(function () {

            $(".nav a").on("click", function () {
                $(".nav").find(".nav-active").removeClass("nav-active");
                $(this).parent().addClass("nav-active");
            });


            var msg = document.getElementById('condition');

            if (msg != null) {
                var handleMediaChange = function (mql) {

                    // For some reason Firefox has trouble always running this code.
                    // The console.log seems to help it.
                    // TODO: Figure out what the hell that's all about
                    console.log();

                    if (mql.matches) {
                        msg.setAttribute('class', 'met');
                        msg.innerHTML = 'The condition "' + mql.media + '" was met.';
                    }
                    else {
                        msg.setAttribute('class', 'unmet');
                        msg.innerHTML = 'The condition "' + mql.media + '" was not met.';
                    }
                };

                mqEvents(handleMediaChange);
            }
        });

        (function () {
            var mqEvents = function (mediaChangeHandler) {
                var sheets = document.styleSheets,
                        numSheets = sheets.length,
                        mqls = {},
                        mediaChange = function (mql) {
                            console.log(mql);
                        }

                if (mediaChangeHandler) {
                    mediaChange = mediaChangeHandler;
                }

                for (var i = 0; i < numSheets; i += 1) {
                    if (sheets[i].cssRules == null) {
                        continue;
                    }

                    var rules = sheets[i].cssRules;
                    var numRules = rules.length;
                    for (var j = 0; j < numRules; j += 1) {
                        if (rules[j].constructor === CSSMediaRule) {
                            mqls['mql' + j] = window.matchMedia(rules[j].media.mediaText);
                            mqls['mql' + j].addListener(mediaChange);
                            mediaChange(mqls['mql' + j]);
                        }
                    }
                }
            }

            window.mqEvents = mqEvents;

            $('nav').affix({
                offset: {
                    top: $('header').height()
                }
            });
        }());
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>
