WorkEffect.Website/Controllers/LayoutParametersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WorkEffect.Website.Models;

namespace WorkEffect.Website.Controllers
{
    public class LayoutParametersController : BaseCmsEntityController<ContentLayoutParameter>
    {
        [ChildActionOnly]
        public ActionResult List(int id)
        {
            ViewBag.LayoutId = id;
            return View(GetList(id));
        }

        public virtual List<ContentLayoutParameter> GetList(int id)
        {
            return Context.LayoutParameters.Where(a => a.ContentLayoutId == id).ToList();
        }

        public override void OnCreate(ContentLayoutParameter model, int parentID)
        {
            model.ContentLayoutId = parentID;
            base.OnCreate(model, parentID);
        }

        public override ActionResult Create(ContentLayoutParameter model, FormCollection data)
        {
            return base.Create(model, data);
        }
    }
}

WorkEffect.Website/Controllers/LayoutsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkEffect.Website.Data;
using WorkEffect.Website.Models;

namespace WorkEffect.Website.Controllers
{
    public class LayoutsController : BaseCmsEntityControllerAsync<ContentLayout>
    {
    }
}

WorkEffect.Website/Views/Layouts/Create.cshtml
@model WorkEffect.Website.Models.ContentLayout

@{
    ViewBag.Title = "Create";
}
<div class="container" id="WorkEffect1">
    <div class="col-md-12 body-container">

        <h2>Create</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.Partial("_CreateOrEdit")

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

WorkEffect.Website/Views/Layouts/Delete.cshtml
@model WorkEffect.Website.Models.ContentLayout

@{
    ViewBag.Title = "Delete";
}
<div class="container" id="WorkEffect1">
    <div class="col-md-12 body-container">

        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            @Html.Partial("_Details")

            @using (Html.BeginForm(new { id = Model.Id }))
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

WorkEffect.Website/Views/Layouts/Details.cshtml
@model WorkEffect.Website.Models.ContentLayout

@{
    ViewBag.Title = "Details";
}
<div class="container" id="WorkEffect1">
    <div class="col-md-12 body-container">

        <h2>Details</h2>

        <div>
            @Html.Partial("_Details")
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

    </div>
</div>

WorkEffect.Website/Views/Layouts/Edit.cshtml
@model WorkEffect.Website.Models.ContentLayout

@{
    ViewBag.Title = "Edit";
}
<div class="container" id="WorkEffect1">
    <div class="col-md-12 body-container">

        <h2>Edit</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.Partial("_CreateOrEdit")

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Edit" class="btn btn-default" />
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

WorkEffect.Website/Views/Layouts/Index.cshtml
@model IEnumerable<WorkEffect.Website.Models.ContentLayout>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="col-md-12 body-container">
        
        <h2>Index</h2>

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Css)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Html)
                </th>
                <th class="table-actions"></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Css)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Html)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                        @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                        @Html.ActionLink("Delete", "Delete", new {id = item.Id})
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

WorkEffect.Website/Views/Layouts/_CreateOrEdit.cshtml
@model WorkEffect.Website.Models.ContentLayout
<div class="form-horizontal">
    <h4>ContentLayout</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Html, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Html, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Html, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Css, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Css, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Css, "", new { @class = "text-danger" })
        </div>
    </div>

    <script type="text/javascript">
        function attachAjaxSubmitHandler(button, target) {
            $(button).click(function (event) {
                if (typeof target !== 'undefined' && target !== false) {
                    event.preventDefault();
                    $.post(target.attr('action'), target.serialize(), function (data) {
                        target.closest('.ajax-boundary').html(data);
                    });
                }
            });
        }
    </script>

    @if (Model.Id > 0)
    {
        <div class="form-group ajax-boundary">
            @Html.Label("Layout Parameters", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    Html.RenderAction("List", "LayoutParameters", new { id = Model.Id });
                }
            </div>
        </div>
                    }
</div>

WorkEffect.Website/Views/Layouts/_Details.cshtml
@model WorkEffect.Website.Models.ContentLayout

<h4>ContentLayout</h4>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Css)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Css)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Html)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Html)
    </dd>

</dl>